import type { Metadata } from "next";

import { ThemeProvider } from "@/components/ThemeProvider";

import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ${geistSans.variable} ${geistMono.variable}
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
